name: Infra - Terraform Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'iac/**.tf'
      - 'iac/**.tfvars'
      - 'iac/**/*.tf'
  
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    environment: dev   

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      # 1. Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 3. Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # 4. Validar formato y sintaxis
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # 5. Plan de ejecuci贸n
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 6. Requiere aprobaci贸n manual antes de aplicar
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: Josecp03   
          minimum-approvals: 1
          issue-title: "Aprobaci贸n requerida para Terraform Apply"
          issue-body: "Se requiere aprobaci贸n manual para ejecutar Terraform Apply en el entorno de Azure."

      # 7. Aplicar cambios
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
